[metadata]
name = twitch_hdt_ebs
version = 1.0.0
description = Twitch EBS for Hearthstone Deck Tracker
author = Jerome Leclanche
author_email = jerome@leclan.ch
url = https://github.com/HearthSim/twitch-hdt-ebs/
download_url = https://github.com/HearthSim/twitch-hdt-ebs/tarball/master
classifiers =
	Development Status :: 5 - Production/Stable
	Framework :: Django :: 4.2
	Intended Audience :: Developers
	License :: OSI Approved :: MIT License
	Programming Language :: Python
	Programming Language :: Python :: 3
	Programming Language :: Python :: 3.9
	Topic :: Games/Entertainment

[options]
packages = find:
include_package_data = True
zip_safe = False
install_requires =
	Django==4.2.27
	django-allauth@https://libs.hearthsim.net/django_allauth-0.56.1.post1+backport.battlenet.2024.tar.gz
	django-cors-headers==4.9.0
	django-oauth-toolkit==1.7.1
	oauthlib==3.3.1
	django-redis==4.12.1
	djangorestframework==3.14.0
	psycopg2-binary==2.9.2
	PyJWT==1.7.1
	python-redis-lock==3.7.0
	redis==3.3.8
	sentry_sdk==1.5.8
	shortuuid==0.5.0
	hearthsim-identity@https://libs.hearthsim.net/hearthsim_identity-7.1.2-py3-none-any.whl
	hearthsim-instrumentation==0.1.0
	django-hearthstone==1.6.0
	urllib3<2

[options.packages.find]
exclude =
	tests
