name: Continuous Integration

on: [push]

jobs:
  tox:
    strategy:
      fail-fast: false
      matrix:
        toxenv: [py36-django22, flake8, mypy]
    name: Tox
    runs-on: ubuntu-latest
    env:
      TOXENV: ${{matrix.toxenv}}
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: test_hdt_ebs
        ports:
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
        pip install tox
    - name: Prepare database
      env:
        PGPORT: ${{ job.services.postgres.ports['5432'] }}
      run: python manage.py migrate --settings tests.settings
    - name: tox (${{matrix.toxenv}})
      run: tox
